apiVersion: apps/v1
kind: Deployment
metadata:
  name: 20-acr-name
  labels:
    app: 20-acr-app01
spec:
  replicas: 2
  selector:
    matchLabels: 
    app: 20-acr-app01
  template:
    metadata:
      labels:
        app: 20-acr-app01
    spec:
      containers:
      - name: 20-arc-docker-container-name
        image: acradedemo2.azurecr.io/app1/20-arc-docker-file:v1
        ports:
          containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: service
metadata:
  name: 20-arc-docker-loadbalancer-service
  labels:
    app: 20-arc-docker
spec: 
  selector:
    app: 20-arc-docker
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

