apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo02-name
  labels:
    app: devopsdemo02-app02
spec:
  replicas: 2
  selector:
    matchLabels: 
    app: devopsdemo02-app02
  template:
    metadata:
      labels:
        app: devopsde2mo02-app0
    spec:
      containers:
      - name: devopsdemo02-container-name
        image: acrdevopsdemo02/apps/devopsdemo02-app02:v2
        ports:
          containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: service
metadata:
  name: devopsdemo02-app02-loadbalancer-service
  labels:
    app: devopsdemo02-app02
spec: 
  selector:
    app: devopsdemo02-app02
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

